# Generated by Django 3.2.7 on 2021-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konsultasi',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
