# Generated by Django 3.2.7 on 2021-09-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sehat_in_webproject.comment'),
        ),
    ]
