# Generated by Django 3.2.7 on 2021-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0007_report_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='adminOnly',
            field=models.BooleanField(default=False),
        ),
    ]
