# Generated by Django 3.2.7 on 2021-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0008_tag_adminonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_Type',
            field=models.CharField(default='forum', max_length=50),
        ),
    ]
