# Generated by Django 3.2.7 on 2021-09-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0009_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
