# Generated by Django 3.2.7 on 2021-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0011_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
