# Generated by Django 3.2.7 on 2021-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0012_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='isResolved',
            field=models.BooleanField(default=False),
        ),
    ]
