# Generated by Django 3.2.7 on 2021-09-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0013_auto_20210919_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
