# Generated by Django 3.2.7 on 2021-10-01 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sehat_in_webproject', '0016_like_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestHistory',
            new_name='History',
        ),
    ]
