# Generated by Django 3.2.7 on 2021-10-01 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0017_rename_testhistory_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='result',
        ),
        migrations.AddField(
            model_name='history',
            name='res_data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='res_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
