# Generated by Django 3.2.7 on 2021-10-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0018_auto_20211001_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_Type',
            new_name='type',
        ),
    ]
