# Generated by Django 3.2.7 on 2021-10-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0020_auto_20211002_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post',
            new_name='post_Forum',
        ),
        migrations.AddField(
            model_name='notification',
            name='post_Konsultasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sehat_in_webproject.konsultasi'),
        ),
    ]
