# Generated by Django 3.2.7 on 2021-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0021_auto_20211002_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
