# Generated by Django 3.2.7 on 2021-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehat_in_webproject', '0022_alter_artikel_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
